# Generated by Django 4.0.6 on 2026-08-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0017_dailymob_daily_rtb_pep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymobdocs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dailymobdocs',
            index=models.Index(fields=['DailyID', 'docType'], name='idx_dailymobdocs_daily_doctype'),
        ),
        migrations.AddIndex(
            model_name='dailymobdocs',
            index=models.Index(fields=['created_date'], name='idx_dailymobdocs_created_date'),
        ),
    ]
