# Generated by Django 4.0.6 on 2026-07-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0114_internalpo_updatedby_internalpo_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
    ]
